// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSampleData() {
  return window['go']['main']['App']['CreateSampleData']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetDatabasePath() {
  return window['go']['main']['App']['GetDatabasePath']();
}

export function GetServerPort() {
  return window['go']['main']['App']['GetServerPort']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function TestDatabaseConnection() {
  return window['go']['main']['App']['TestDatabaseConnection']();
}

export function TestServerConnection() {
  return window['go']['main']['App']['TestServerConnection']();
}
