// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSampleData():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetDatabasePath():Promise<string>;

export function GetServerPort():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function TestDatabaseConnection():Promise<string>;

export function TestServerConnection():Promise<string>;
